---
title: "Lisa Ann's EDA"
author: "Lisa Ann Yu"
date: "February 17, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```

# Load Data

```{r}
source("/Users/lisaannyu/Downloads/fitbit_data.R")
```

# Wrangle data - put it all in same dataset
```{r}
# have all these for one day, 15 min intervals - want to be able to generalize
# Make it tidy
df <- df_distance %>% 
  left_join(df_active_min, by = "time") %>% 
  left_join(df_cal_burned, by = "time") %>% 
  left_join(df_floors, by = "time") %>% 
  left_join(df_heart_rate, by = "time") %>% 
  select(time, distance, `active-minutes`, `calories-burned`, floors, bpm,  # activityLevel chr
         caloriesBurned) %>% 
  gather(key = "measure", value = "value", -time)

# Normalize
df_norm <- df %>% 
  group_by(measure) %>% 
  mutate(value = value / sum(value))
```


# Multiple measures over the course of a day
```{r}
df_norm %>% 
  ggplot(mapping = aes(x = time, y = value, color = measure)) +
  geom_line() 

# calories-burned from df_cal_burned, caloriesBurned from df_heart_rate
df_norm %>% 
  filter(measure %in% c("calories-burned", "caloriesBurned")) %>% 
  ggplot(mapping = aes(x = time, y = value, color = measure)) +
  geom_line() 

# Filtered
df_norm %>% 
  ggplot(mapping = aes(x = time, y = value, color = measure)) +
  coord_cartesian(xlim = c(as.POSIXct("2017-01-27 07:00:00 PST"),
                           as.POSIXct("2017-01-27 23:45:00 PST"))) +
  geom_line() 
```

```{r}
plot_time_interval <- function(start_time, end_time, measures) {
  df_norm %>% # should I pass in df_norm?
    filter(measure %in% measures) %>% 
    ggplot(mapping = aes(x = time, y = value, color = measure)) +
    coord_cartesian(xlim = c(start_time, end_time)) +
    geom_line() 
}

plot_time_inverval(as.POSIXct("2017-01-27 07:00:00 PST"), 
                   as.POSIXct("2017-01-27 23:45:00 PST"))
```

